### ISSUE TITLE
I encountered vaadin v20.0.1 compilation problem in broker-server v1.1.1

### ISSUE THREAD

**Issue by daivichin** [alibaba/alibaba-rsocket-broker#142]
**Describe the bug**
I encountered vaadin v20.0.1 compilation problem in broker-server v1.1.1

### Environment

* Alibaba RSocket Broker version: 1.1.1
* Operating System version: Mac Big Sur v11.4
* Java version: 1.8.0+ or openjdk version v11.0.9

### Steps to reproduce this issue

1. mvn package -Dmaven.test.skip=true

```
Downloading from alimaven: http://maven.aliyun.com/nexus/content/groups/public/org/webjars/npm/mobile-drag-drop/maven-metadata.xml
Downloading from nexus: https://m2.org.com/content/groups/public/org/webjars/npm/mobile-drag-drop/maven-metadata.xml
Downloaded from nexus: https://m2.org.com/content/groups/public/org/webjars/npm/mobile-drag-drop/maven-metadata.xml (425 B at 890 B/s)
Downloaded from alimaven: http://maven.aliyun.com/nexus/content/groups/public/org/webjars/npm/mobile-drag-drop/maven-metadata.xml (426 B at 383 B/s)
[INFO] 
[INFO] --- git-commit-id-plugin:4.0.4:revision (default) @ zxy-broker-server ---
[INFO] skip is enabled, skipping execution!
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ zxy-broker-server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 8 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ zxy-broker-server ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- vaadin-maven-plugin:20.0.1:prepare-frontend (default) @ zxy-broker-server ---
[INFO] Added 4 default dependencies to main package.json
[INFO] Copying frontend resources from jar files ...
[INFO] Visited 294 resources. Took 197 ms.
[INFO] 
[INFO] --- vaadin-maven-plugin:20.0.1:build-frontend (default) @ zxy-broker-server ---
[INFO] Scanning classes to find frontend configurations and dependencies...
[INFO] Visited 3653 classes. Took 2892 ms.
[INFO] Visited 103 classes. Took 52 ms.
[INFO] Running `pnpm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
[INFO] using '/usr/local/bin/npx --yes --quiet pnpm@5' for frontend package installation
[INFO] Frontend dependencies resolved successfully.
[INFO] Copying frontend resources from jar files ...
[INFO] Visited 294 resources. Took 172 ms.
[INFO] Running webpack ...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  48.634 s
[INFO] Finished at: 2021-09-02T17:16:05+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:20.0.1:build-frontend (default) on project zxy-broker-server: Execution default of goal com.vaadin:vaadin-maven-plugin:20.0.1:build-frontend failed: Webpack process exited with non-zero exit code.
[ERROR] Stderr: '/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/registry.nlark.com/webpack-cli@3.3.11_webpack@4.46.0/node_modules/webpack-cli/bin/cli.js:93
[ERROR]                                 throw err;
[ERROR]                                 ^
[ERROR] 
[ERROR] Error: Cannot find module 'workbox-build/build/options/schema/webpack-generate-sw'
[ERROR] Require stack:
[ERROR] - /Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/registry.nlark.com/workbox-webpack-plugin@6.1.0_webpack@4.46.0/node_modules/workbox-webpack-plugin/build/generate-sw.js
[ERROR] - /Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/registry.nlark.com/workbox-webpack-plugin@6.1.0_webpack@4.46.0/node_modules/workbox-webpack-plugin/build/index.js
[ERROR] - /Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/webpack.generated.js
[ERROR] - /Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/webpack.config.js
[ERROR] - /Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/registry.nlark.com/webpack-cli@3.3.11_webpack@4.46.0/node_modules/webpack-cli/bin/utils/convert-argv.js
[ERROR] - /Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/registry.nlark.com/webpack-cli@3.3.11_webpack@4.46.0/node_modules/webpack-cli/bin/cli.js
[ERROR] - /Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/registry.nlark.com/webpack@4.46.0_webpack-cli@3.3.11/node_modules/webpack/bin/webpack.js
[ERROR]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[ERROR]     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
[ERROR]     at Module.require (internal/modules/cjs/loader.js:974:19)
[ERROR]     at require (/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/v8-compile-cache@2.0.3/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
[ERROR]     at Object.<anonymous> (/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/registry.nlark.com/workbox-webpack-plugin@6.1.0_webpack@4.46.0/node_modules/workbox-webpack-plugin/build/generate-sw.js:20:33)
[ERROR]     at Module._compile (/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/v8-compile-cache@2.0.3/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
[ERROR]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[ERROR]     at Module.load (internal/modules/cjs/loader.js:950:32)
[ERROR]     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
[ERROR]     at Module.require (internal/modules/cjs/loader.js:974:19)
[ERROR]     at require (/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/v8-compile-cache@2.0.3/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
[ERROR]     at Object.<anonymous> (/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/registry.nlark.com/workbox-webpack-plugin@6.1.0_webpack@4.46.0/node_modules/workbox-webpack-plugin/build/index.js:10:20)
[ERROR]     at Module._compile (/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/v8-compile-cache@2.0.3/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
[ERROR]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[ERROR]     at Module.load (internal/modules/cjs/loader.js:950:32)
[ERROR]     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
[ERROR]     at Module.require (internal/modules/cjs/loader.js:974:19)
[ERROR]     at require (/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/v8-compile-cache@2.0.3/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
[ERROR]     at Object.<anonymous> (/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/webpack.generated.js:10:28)
[ERROR]     at Module._compile (/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/v8-compile-cache@2.0.3/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
[ERROR]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[ERROR]     at Module.load (internal/modules/cjs/loader.js:950:32)
[ERROR]     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
[ERROR]     at Module.require (internal/modules/cjs/loader.js:974:19)
[ERROR]     at require (/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/v8-compile-cache@2.0.3/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
[ERROR]     at Object.<anonymous> (/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/webpack.config.js:10:22)
[ERROR]     at Module._compile (/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/v8-compile-cache@2.0.3/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
[ERROR]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[ERROR]     at Module.load (internal/modules/cjs/loader.js:950:32)
[ERROR]     at Function.Module._load (internal/modules/cjs/loader.js:790:14) {
[ERROR]   code: 'MODULE_NOT_FOUND',
[ERROR]   requireStack: [
[ERROR]     '/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/registry.nlark.com/workbox-webpack-plugin@6.1.0_webpack@4.46.0/node_modules/workbox-webpack-plugin/build/generate-sw.js',
[ERROR]     '/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/registry.nlark.com/workbox-webpack-plugin@6.1.0_webpack@4.46.0/node_modules/workbox-webpack-plugin/build/index.js',
[ERROR]     '/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/webpack.generated.js',
[ERROR]     '/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/webpack.config.js',
[ERROR]     '/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/registry.nlark.com/webpack-cli@3.3.11_webpack@4.46.0/node_modules/webpack-cli/bin/utils/convert-argv.js',
[ERROR]     '/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/registry.nlark.com/webpack-cli@3.3.11_webpack@4.46.0/node_modules/webpack-cli/bin/cli.js',
[ERROR]     '/Users/xxx/0_WORKPDCA/20_org/0_project/0_processing/java/zxy-broker-server/node_modules/.pnpm/registry.nlark.com/webpack@4.46.0_webpack-cli@3.3.11/node_modules/webpack/bin/webpack.js'
[ERROR]   ]
[ERROR] }

```

**Comment by daivichin** [comment]
Suggest the author to upgrade vaadin to 20.0.6

https://github.com/vaadin/flow/issues/11536

Thanks!
