### ISSUE TITLE
部署requester时报Caused by: java.lang.NoSuchFieldError: MESSAGE_RSOCKET_APPLICATION

### ISSUE THREAD

**Issue by bearxu83** [alibaba/alibaba-rsocket-broker#173]
本地测试正常，但部署到测试服务器，启动时报：
Caused by: java.lang.NoSuchFieldError: MESSAGE_RSOCKET_APPLICATION
        at com.alibaba.rsocket.metadata.RSocketMimeType.<clinit>(RSocketMimeType.java:25)
        at com.alibaba.rsocket.invocation.RSocketRemoteServiceBuilder.<init>(RSocketRemoteServiceBuilder.java:32)
        at com.alibaba.rsocket.invocation.RSocketRemoteServiceBuilder.client(RSocketRemoteServiceBuilder.java:51)
        at myservice.service.impl.PullData(PullData.java:16)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)

pom里面使用alibaba-rsocket-core 1.0.1.
启动时会报Rconnector找不到，所以我在pom的alibaba-rsocket-core和alibaba-rsocket-spring-boot-starter后面会加上rsocket-core1.0.5。但无论怎么调整都报上面的错。但在本地运行正常。

感觉没有调到alibaba-rsocket-core里面的io.rsocket.metadata.WellKnownMimeType

请问该如何解决？使用maven的exclude?谢谢

**Comment by bearxu83** [comment]
感谢回复。
> 能否升级到 alibaba-rsocket 1.1.1试一下。 
我们的SpringBoot是2.2.2所以应该只能跑1.0.1.

>这个是启动RSocket Server出错，还是RSocket的应用启动出错？
是在Spring启动requester时，自动载入@Configure时， return RSocketRemoteServiceBuilder。。。的时候报错。

>如果方便的话，能够告知你在服务端是如何部署的吗？ 是fatjar吗？
不是fatjar，每个包有自己的jar。但在部署的时候，responder的代码也打了进去，但我加了个conditionalonproperty，把“UserServiceImpl”去掉自动注入了。

**Comment by linux-china** [comment]
>>不是fatjar，每个包有自己的jar。但在部署的时候，responder的代码也打了进去。 

你能调整一下classpath吗？  将alibaba-rsocket-core-1.0.1.jar放在第一位，看起来classpath被调整啦，这个主要是 alibaba-rsocket-core-1.0.1.jar 有一个覆盖rsocket-core.jar中的类。   你能否将classpath以名称进行排序，你本地就是的， 可能线上环境被改变啦。
