### ISSUE TITLE
出現class reactor.core.publisher.MonoContextWrite cannot be cast to class java.lang.Integer error

### ISSUE THREAD

**Issue by yapjiahong** [alibaba/alibaba-rsocket-broker#174]
您好，當我使用 `spring-boot-starter-data-jpa` 出現這個錯誤信息

`Caused by: java.lang.ClassCastException: class reactor.core.publisher.MonoContextWrite cannot be cast to class java.lang.Integer (reactor.core.publisher.MonoContextWrite is in unnamed module of loader 'app'; java.lang.Integer is in module java.base of loader 'bootstrap')
        at MyRScoketServiceRSocketStub.hashCode(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[na:na]
        at java.base/java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964) ~[na:na]
        at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.requiresDestruction(PersistenceAnnotationBeanPostProcessor.java:372) ~[spring-orm-5.3.9.jar:5.3.9]
        at org.springframework.beans.factory.support.DisposableBeanAdapter.hasApplicableProcessors(DisposableBeanAdapter.java:383) ~[spring-beans-5.3.9.jar:5.3.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.requiresDestruction(AbstractBeanFactory.java:1911) ~[spring-beans-5.3.9.jar:5.3.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.registerDisposableBeanIfNecessary(AbstractBeanFactory.java:1929) ~[spring-beans-5.3.9.jar:5.3.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:643) ~[spring-beans-5.3.9.jar:5.3.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.9.jar:5.3.9]
        ... 42 common frames omitted`

**Comment by linux-china** [comment]
>> unnamed module of loader 'app';
是不是你的Reactor Bom版本太低啦，能否升级一下？   https://repo1.maven.org/maven2/io/projectreactor/reactor-bom/ 

如果方便的话，能否将你的demo push到github上，我看一下。

**Comment by yapjiahong** [comment]
沒問題，這裡
https://github.com/yapjiahong/rsocket-demo

很妙的是，只要把 springdata-data-jpa 給註解，程式就能動作了

感謝和這位老哥遇到的很像
https://stackoverflow.com/questions/69837617/alibaba-rsocket-monocontextwrite-cannot-be-cast-to-class-java-lang-integer

**Comment by linux-china** [comment]
这个不是你的问题，这个是Java Proxy机制的要注意的事项， spring-boot-starter-data-jpa 会调用bean的hashCode()方法，而该函数又被Proxy代理啦，所以导致了调用错误，我添加判断逻辑修复了该错误。

```java
 if (method.getDeclaringClass().equals(Object.class)) { //delegate hashCode, equals, or toString methods to this
            return method.invoke(this);
        }
```

你使用一下最新的1.1.2版本，我已经修复这个bug，你提供的demo我本地测试了一下，也没有问题。

```
implementation('com.alibaba.rsocket:alibaba-rsocket-spring-boot-starter:1.1.2')
```

我还不确定spring-boot-starter-data-jpa 为何要调用spring bean的hashCode()方法，Spring框架应该不会做这个事情，可能是其特殊操作，我查一下官方代码后再告知你一下。

**Comment by yapjiahong** [comment]
Hi，目前使用最新版本，問題果然被解決了，感謝🙏。
