### ISSUE TITLE
Broker return Docker internal IP when Client  findBrokerDiscoveryService().getInstances("*")  then LoadBalancedRSocket: RST-400500: Failed to connect URI: tcp://<docker internal ip>:9999

### ISSUE THREAD

**Issue by sealte** [alibaba/alibaba-rsocket-broker#177]
**Describe the bug**
Broker return Docker internal IP when Client  findBrokerDiscoveryService().getInstances("*")  then LoadBalancedRSocket: RST-400500: Failed to connect URI: tcp://<docker internal ip>:9999

### Environment

* Alibaba RSocket Broker version: 1.1.2
* Operating System version: Windows 11 (IDEA, Client), CentOS 7/Docker (Broker)
* Java version: 17

### Steps to reproduce this issue

1. config Broker with "rsocket.broker.external-domain=tcp://<external ip>:<external port>"
2. config Client with "rsocket.topology=internet" and "rsocket.brokers=tcp://<external ip>:<external port>"

### Expected Result

get external ip and external port, no errors

### Actual Result

2021-12-01 10:20:43.496 ERROR 20572 --- [actor-tcp-nio-2] c.a.r.loadbalance.LoadBalancedRSocket    : RST-400500: Failed to connect URI: tcp://<docker internal ip>:9999

io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /<docker internal ip>:9999
Caused by: java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946) ~[na:na]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[netty-transport-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707) ~[netty-transport-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

**Comment by linux-china** [comment]
`tcp://:9999` is not correct RSocket URL, and you should add host and port for RSocket URL, such as `tcp://external.domain.foobar.com:9999`

For more, please refer:   https://github.com/alibaba/alibaba-rsocket-broker/tree/master/alibaba-broker-server#intranet%E6%A8%A1%E5%BC%8F

**Comment by sealte** [comment]
github把问题表述里的一些特殊符号给过滤掉了，我重新描述：

问题复现步骤：
1、Broker端配置 rsocket.broker.external-domain=tcp://外部可访问IP:9999
2、客户端配置 rsocket.topology=internet，rsocket.brokers=tcp://外部可访问IP:9999

实际结果：
2021-12-01 10:20:43.496 ERROR 20572 --- [actor-tcp-nio-2] c.a.r.loadbalance.LoadBalancedRSocket : RST-400500: Failed to connect URI: tcp://docker容器内部IP:9999

io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /docker容器内部IP:9999
Caused by: java.net.ConnectException: Connection timed out: no further information
at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[na:na]
at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946) ~[na:na]
at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[netty-transport-4.1.70.Final.jar:4.1.70.Final]
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.70.Final.jar:4.1.70.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707) ~[netty-transport-4.1.70.Final.jar:4.1.70.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.70.Final.jar:4.1.70.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.70.Final.jar:4.1.70.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.70.Final.jar:4.1.70.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.70.Final.jar:4.1.70.Final]
at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

**Comment by linux-china** [comment]
你是使用helm部署在K8S的吧？ 如果是K8S部署的话，目前不支持对外暴露互连网IP，而是要求应用部署部署到K8S中，然后以容器IP访问Broker。 如果对外暴露互联网IP，要求每一个容器都有固定的互联网IP，而在K8S内部如果有扩容缩容的时候都比较麻烦，会丢失对应的互联网IP配置信息，导致维护非常麻烦。 这种情况建议下，有两个建议： 编写一个RSocket服务做代理，如WebSocket，然后再访问内部的RSocket服务。 要不将RSocket Broker部署到K8S外部，这样K8S容器和外部应用都能访问该集群，RSocket Broker集群管理方式为Gossip。
