### ISSUE TITLE
external-domain设置了代码里不需要判断吗？

### ISSUE THREAD

**Issue by itmagus** [alibaba/alibaba-rsocket-broker#201]
看到好几个关于external-domain参数的问题了，还是拿了内网的IP，看了下代码，是否这是个问题呢？

Flux.interval(Duration.ofSeconds(120))
                        .flatMap(timestamp -> findBrokerDiscoveryService().getInstances("*"))
                        .map(serviceInstances -> serviceInstances.stream().map(RSocketServiceInstance::getUri).collect(Collectors.toList()))
                        .subscribe(uris -> brokerCluster.setUris(uris));

看代码中，有去调用DiscoveryService.getInstances
然而，在broker中并没有去判断externalDomain是否设置了，直接取了broker.getUrl()，而不是getAliasUrl？
@Override
    public Mono<List<RSocketServiceInstance>> getInstances(String serviceId) {
        if (serviceId.equals("*")) {
            return Flux.fromIterable(rsocketBrokerManager.currentBrokers())
                    .filter(RSocketBroker::isActive)
                    .map(broker -> {
                        RSocketServiceInstance instance = new RSocketServiceInstance();
                        instance.setInstanceId(broker.getId());
                        instance.setHost(broker.getIp());
                        instance.setServiceId("*");
                        instance.setPort(broker.getPort());
                        instance.setSchema(broker.getSchema());
                        instance.setUri(broker.getUrl());
                        instance.setSecure(broker.isActive());
                        return instance;
                    }).collectList();
        }
        return findServiceInstances(serviceId).collectList();
    }

**Comment by linux-china** [comment]
这里是一个bug，但是也比较难解决一些。  Broker Client会在连接的时候向服务端说明自己的拓扑结构，Broker会进行broker url推送。 而服务注册发现，客户端还不能提供这些信息，所以服务推送的数据都是内部网络的数据。 此外服务注册发现的场景，都是要求网络是通的，Broker推送服务方的IP地址类别后，都是服务消费方和服务提供方自行连接，所以推送的IP地址都是内部能够相互通讯的，不会存在external domain这个场景。 这个external domain主要是给RSocket Broker客户端用的，不能用在服务发现上。

**Comment by itmagus** [comment]
感谢大老解惑，我说的这种情况，应该是属于客户端作Broker的负载时发生的。
findBrokerDiscoveryService().getInstances("*")，拿的应该是Broker的地址，是RSocket Broker客户端在用的吧，这个时候，客户端，和Broker，以及服务提供者不一定在一个内部网络。
比如开发环境在阿里云上，这个时候本地调试客户端，不通过VPN的方式，这个时候就要报错？
reactor.core.Exceptions$ErrorCallbackNotImplemented: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /192.168.0.2:9999
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /192.168.0.2:9999
Caused by: java.net.ConnectException: Connection timed out: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_271]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715) ~[na:1.8.0_271]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.78.Final.jar:4.1.78.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_271]
![image](https://user-images.githubusercontent.com/8073980/184476736-2687da25-aedf-4d37-b7d0-fcba3f053734.png)
这个时候，也并没有配置去关闭客端的负载，每隔120S还是会去做这个事，虽然说，checkConnect，去检查连接失败报错，也不影响客户端通过外网调用Broker，仍然觉得这种情况不应该发生。
大家在这里有疑问的原因，是因为这个地方需要满足不同的场景，很容易陷入某一种场景思维。从而忽略这个问题

**Comment by linux-china** [comment]
@itmagus  请参考这里进行该场景的部署  https://github.com/alibaba/alibaba-rsocket-broker/tree/master/alibaba-broker-server#internet%E6%A8%A1%E5%BC%8F   之前RSocket Broker在阿里云上提供免费的测试服务，使用的部署就是该结构。

**Comment by itmagus** [comment]
@linux-china 用的就是种方式
broker配置
rsocket.broker.external-domain=外网IP
客户端配置
rsocket:
  brokers: tcp://外网IP:端口
  jwt-token: xxx
  topology: internet
调用正常，120秒后，开始报上述的异常，调用仍然正常。
如果这是正常的那就这样吧先

**Comment by linux-china** [comment]
@itmagus 最好不要使用独立主机上独立的容器部署，然后使用external domain来进行通讯，这样做到的，gossip广播，集群之间的通讯都不是走external domain的，没法工作的。 你最好使用K8S，直接屏蔽网络这些细节，相当于broker有自己的内部唯一IP，这样才可以。

如果你要对外进行集成，最好使用独立VM进行部署，这样对外可以暴露互联网IP， 而应用不管是独立部署在K8S，还是独立Docker容器等，都可以和Broker VM进行通讯。 如果部署在容器内部，一大堆网络配置转发，端口映射问题，不方便。 

个人是建议使用VM独立部署RSocket Broker集群，这个在刚开始规划好，扩容也是容易的。 这样你以后有多个K8S集群，还是外部接入等，都没有问题。

**Comment by itmagus** [comment]
@ [linux-china](https://github.com/linux-china)

最开始就是用的K8S的方式，DOCKER容器，还是代码直接启动，都试过了，不是依然有这个问题吗？确定和部署不是两码事？
相关的问题，也无下文哈
https://github.com/alibaba/alibaba-rsocket-broker/issues/177
https://github.com/alibaba/alibaba-rsocket-broker/issues/182
