### ISSUE TITLE
rsocket-requester. 请求者客户端启动失败

### ISSUE THREAD

**Issue by niyaode** [alibaba/alibaba-rsocket-broker#204]
```
 :: Spring Boot ::                (v2.7.2)

2022-08-14 20:46:02.409  INFO 50487 --- [           main] cn.sdack.imio.GatewayApplicationKt       : Starting GatewayApplicationKt using Java 11.0.9.1 on bulusideAir with PID 50487 (/Users/sdack/IdeaProjects/imio/gateway/build/classes/kotlin/main started by sdack in /Users/sdack/IdeaProjects/imio)
2022-08-14 20:46:02.413  INFO 50487 --- [           main] cn.sdack.imio.GatewayApplicationKt       : No active profile set, falling back to 1 default profile: "default"
2022-08-14 20:46:03.837  INFO 50487 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'rsocket-com.alibaba.spring.boot.rsocket.RSocketProperties' of type [com.alibaba.spring.boot.rsocket.RSocketProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-08-14 20:46:03.846  INFO 50487 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'com.alibaba.spring.boot.rsocket.RSocketAutoConfiguration' of type [com.alibaba.spring.boot.rsocket.RSocketAutoConfiguration$$EnhancerBySpringCGLIB$$df8f7714] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-08-14 20:46:03.965  WARN 50487 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'roomService' defined in class path resource [cn/sdack/imio/configuration/RoomServicesAutoConfiguration.class]: Unsatisfied dependency expressed through method 'roomService' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rsocketUpstreamManager': Unsatisfied dependency expressed through field 'serverProperties'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.autoconfigure.web.ServerProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2022-08-14 20:46:03.967  INFO 50487 --- [           main] c.s.imio.controller.RSocketController    : Shutting down...
2022-08-14 20:46:03.983  INFO 50487 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-08-14 20:46:03.999 ERROR 50487 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field serverProperties in com.alibaba.spring.boot.rsocket.upstream.SmartLifecycleUpstreamManagerImpl required a bean of type 'org.springframework.boot.autoconfigure.web.ServerProperties' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'org.springframework.boot.autoconfigure.web.ServerProperties' in your configuration.

与目标 VM 断开连接, 地址为: ''127.0.0.1:55151'，传输: '套接字''

```

<img width="640" alt="image" src="https://user-images.githubusercontent.com/27875141/184537660-a95a7e3a-a996-460e-b977-18ad1a83eb6b.png">

服务端 怎么一直有这个输出啊？？？
> reactor.core.Exceptions$ErrorCallbackNotImplemented: io.netty.channel.ConnectTimeoutException: connection timed out: /172.17.0.2:9999
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /172.17.0.2:9999

@linux-china

**Comment by linux-china** [comment]
@niyaode 你能给一个样例项目吗？  主要是项目的代码看不到，没法给出判断，有可能是依赖冲突，或者配置项的问题。  项目自带的样例，你可以运行成功吧？

**Comment by niyaode** [comment]
>     implementation 'com.alibaba.rsocket:alibaba-rsocket-spring-boot-starter:1.1.3'

### responder

```
@RSocketService(serviceInterface = RoomService::class)
@Service
class RoomServiceImpl : ServiceImpl() , RoomService {
```

### requester. 
>    implementation 'org.springframework.boot:spring-boot-starter-rsocket'
>    implementation 'com.alibaba.rsocket:alibaba-rsocket-spring-boot-starter:1.1.3'

```
@Configuration
class RoomServicesAutoConfiguration {

    @Bean
    fun roomService(@Autowired upstreamManager: UpstreamManager): RoomService {
        return RSocketRemoteServiceBuilder
            .client(RoomService::class.java)
            .upstreamManager(upstreamManager)
            .acceptEncodingType(RSocketMimeType.Json)
            .build()
    }

}
```

**Comment by linux-china** [comment]
这个demo能提交到github上吗？

**Comment by sdack-cloud** [comment]
> https://github.com/sdack-cloud/imio.git

我已推送
@linux-china

**Comment by sdack-cloud** [comment]
也顺便问一下 rsocket-dart  什么时间发布 1.0 版本，此项目 4个月没进展了

**Comment by linux-china** [comment]
rsocket-dart用的人很少，目前只有channel特性没有实现，其他特性都可以使用的， 如果你遇到什么问题的话，你可以提issue或者自己定位一下错误。

**Comment by linux-china** [comment]
> 

没有README.md？ 那个module启动不了？ 能稍微说明一下吗？

**Comment by sdack-cloud** [comment]
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [cn.sdack.imio.service.RoomService]: Factory method 'roomService' threw exception; nested exception is java.lang.NoSuchFieldError: MESSAGE_RSOCKET_APPLICATION
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.22.jar:5.3.22]
	... 19 common frames omitted
Caused by: java.lang.NoSuchFieldError: MESSAGE_RSOCKET_APPLICATION
	at com.alibaba.rsocket.metadata.RSocketMimeType.<clinit>(RSocketMimeType.java:26) ~[alibaba-rsocket-core-1.1.3.jar:na]
	at com.alibaba.rsocket.invocation.RSocketRemoteServiceBuilder.<init>(RSocketRemoteServiceBuilder.java:32) ~[alibaba-rsocket-core-1.1.3.jar:na]
	at com.alibaba.rsocket.invocation.RSocketRemoteServiceBuilder.client(RSocketRemoteServiceBuilder.java:51) ~[alibaba-rsocket-core-1.1.3.jar:na]
	at cn.sdack.imio.configuration.RoomServicesAutoConfiguration.roomService(RoomServicesAutoConfiguration.kt:23) ~[main/:na]
	at cn.sdack.imio.configuration.RoomServicesAutoConfiguration$$EnhancerBySpringCGLIB$$f811067e.CGLIB$roomService$0(<generated>) ~[main/:na]
	at cn.sdack.imio.configuration.RoomServicesAutoConfiguration$$EnhancerBySpringCGLIB$$f811067e$$FastClassBySpringCGLIB$$493b8e74.invoke(<generated>) ~[main/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.22.jar:5.3.22]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.22.jar:5.3.22]
	at cn.sdack.imio.configuration.RoomServicesAutoConfiguration$$EnhancerBySpringCGLIB$$f811067e.roomService(<generated>) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.22.jar:5.3.22]
	... 20 common frames omitted
```
我开启了 spring-boot-starter-webflux
又出现新的错误

**Comment by linux-china** [comment]
将     `implementation 'com.alibaba.rsocket:alibaba-rsocket-core:1.1.3'` 放在依赖的第一位，这个和rsocket-core有一个class命名的冲突。

**Comment by sdack-cloud** [comment]
<img width="594" alt="image" src="https://user-images.githubusercontent.com/49465225/184569010-40969add-9571-41c7-a7e8-eff53501998d.png">
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field healthIndicators in com.alibaba.spring.boot.rsocket.health.RSocketServiceHealthImpl required a bean of type 'java.util.List' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'java.util.List' in your configuration.
```

**Comment by linux-china** [comment]
这个是spring boot的health健康度检查， 添加一下actuator就可以啦。

**Comment by sdack-cloud** [comment]
方便问一下您的时区嘛，到时好方便沟通

**Comment by sdack-cloud** [comment]
```
 :: Spring Boot ::                (v2.7.2)

2022-08-15 21:52:58.359  INFO 63056 --- [           main] cn.sdack.imio.GatewayApplicationKt       : Starting GatewayApplicationKt using Java 11.0.9.1 on bulusideAir with PID 63056 (/Users/sdack/IdeaProjects/imio/gateway/build/classes/kotlin/main started by sdack in /Users/sdack/IdeaProjects/imio)
2022-08-15 21:52:58.361  INFO 63056 --- [           main] cn.sdack.imio.GatewayApplicationKt       : No active profile set, falling back to 1 default profile: "default"
2022-08-15 21:52:59.033  INFO 63056 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'rsocket-com.alibaba.spring.boot.rsocket.RSocketProperties' of type [com.alibaba.spring.boot.rsocket.RSocketProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-08-15 21:52:59.034  INFO 63056 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'com.alibaba.spring.boot.rsocket.RSocketAutoConfiguration' of type [com.alibaba.spring.boot.rsocket.RSocketAutoConfiguration$$EnhancerBySpringCGLIB$$713ffb66] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-08-15 21:52:59.428  INFO 63056 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2022-08-15 21:52:59.471  WARN 63056 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rsocketServiceHealth': Unsatisfied dependency expressed through field 'healthIndicators'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.List<org.springframework.boot.actuate.health.ReactiveHealthIndicator>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2022-08-15 21:52:59.472  INFO 63056 --- [           main] c.s.imio.controller.RSocketController    : Shutting down...
2022-08-15 21:52:59.482  INFO 63056 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-08-15 21:52:59.492 ERROR 63056 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field healthIndicators in com.alibaba.spring.boot.rsocket.health.RSocketServiceHealthImpl required a bean of type 'java.util.List' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'java.util.List' in your configuration.

与目标 VM 断开连接, 地址为: ''127.0.0.1:61614'，传输: '套接字''

进程已结束，退出代码为 1
```
@linux-china

**Comment by linux-china** [comment]
这个是Webflux和Actuator配合的问题，是ReactiveHealthIndicator没有找到，你检查一下应用的配置。你可以将rsocket broker client starter注释掉，然后在你代码中可以主动引用ReactiveHealthIndicator bean，看是否能工作。

```
@RSocketService(serviceInterface = RSocketServiceHealth.class)
public class RSocketServiceHealthImpl implements RSocketServiceHealth {
    @Autowired
    private List<ReactiveHealthIndicator> healthIndicators;

```

**Comment by sdack-cloud** [comment]
我写了一个例子  也是重复上面的错误

https://github.com/sdack-cloud/broker-test.git
 您帮忙看看，调整一下
@linux-china

**Comment by linux-china** [comment]
@sdack-cloud  PR提交啦，都可以工作。 requester module没有添加 org.springframework.boot:spring-boot-starter-webflux 依赖啊。
