### ISSUE TITLE
打包后运行报NoClassDefFoundError: Could not initialize class com.alibaba.rsocket.encoding.impl.RSocketEncodingFacadeImpl

### ISSUE THREAD

**Issue by tangkaijun** [alibaba/alibaba-rsocket-broker#62]
导入IDEA中启动alibaba-broker-server和例子程序是正常的，打包后java -jar alibaba-rsocket-broker.jar
启动正常，然后IDEA中运行例子程序后，alibaba-rsocket-broker.jar控制台报如下错误：
2020-05-26 14:14:05.047 ERROR 25620 --- [actor-tcp-nio-4] r.n.channel.ChannelOperationsHandler     : [id: 0x96f19b86, L:/10.10.36.105:9999 - R:/10.10.36.105:58908] Error was received while reading the incoming data. The connection will be closed.

java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.rsocket.encoding.impl.RSocketEncodingFacadeImpl
        at com.alibaba.rsocket.encoding.RSocketEncodingFacade.getInstance(RSocketEncodingFacade.java:42) ~[alibaba-rsocket-core-1.0.0-SNAPSHOT.jar!/:na]
        at com.alibaba.rsocket.listen.RSocketResponderSupport.<init>(RSocketResponderSupport.java:30) ~[alibaba-rsocket-core-1.0.0-SNAPSHOT.jar!/:na]
        at com.alibaba.spring.boot.rsocket.broker.responder.RSocketBrokerResponderHandler.<init>(RSocketBrokerResponderHandler.java:133) ~[alibaba-broker-spring-boot-starter-1.0.0-SNAPSHOT.jar!/:na]
        at com.alibaba.spring.boot.rsocket.broker.responder.RSocketBrokerHandlerRegistryImpl.accept(RSocketBrokerHandlerRegistryImpl.java:168) ~[alibaba-broker-spring-boot-starter-1.0.0-SNAPSHOT.jar!/:na]
        at io.rsocket.core.RSocketServer.lambda$acceptSetup$7(RSocketServer.java:399) ~[rsocket-core-1.0.0.jar!/:na]
        at io.rsocket.core.ServerSetup$DefaultServerSetup.acceptRSocketSetup(ServerSetup.java:70) ~[rsocket-core-1.0.0.jar!/:na]
        at io.rsocket.core.RSocketServer.acceptSetup(RSocketServer.java:371) ~[rsocket-core-1.0.0.jar!/:na]
        at io.rsocket.core.RSocketServer.accept(RSocketServer.java:327) ~[rsocket-core-1.0.0.jar!/:na]
        at io.rsocket.core.RSocketServer.lambda$acceptor$0(RSocketServer.java:315) ~[rsocket-core-1.0.0.jar!/:na]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:203) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drainRegular(FluxGroupBy.java:554) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drain(FluxGroupBy.java:630) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.subscribe(FluxGroupBy.java:696) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.publisher.Flux.subscribe(Flux.java:8325) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:188) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1755) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.publisher.MonoProcessor.onNext(MonoProcessor.java:317) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at io.rsocket.internal.ClientServerInputMultiplexer.lambda$new$1(ClientServerInputMultiplexer.java:110) ~[rsocket-core-1.0.0.jar!/:na]
        at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.publisher.FluxGroupBy$GroupByMain.drainLoop(FluxGroupBy.java:380) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.publisher.FluxGroupBy$GroupByMain.drain(FluxGroupBy.java:316) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.publisher.FluxGroupBy$GroupByMain.onNext(FluxGroupBy.java:201) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213) ~[reactor-core-3.3.5.RELEASE.jar!/:3.3.5.RELEASE]
        at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:220) ~[reactor-netty-0.9.7.RELEASE.jar!/:0.9.7.RELEASE]
        at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:354) ~[reactor-netty-0.9.7.RELEASE.jar!/:0.9.7.RELEASE]
        at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:352) ~[reactor-netty-0.9.7.RELEASE.jar!/:0.9.7.RELEASE]
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:96) ~[reactor-netty-0.9.7.RELEASE.jar!/:0.9.7.RELEASE]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [netty-codec-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425) [netty-codec-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar!/:4.1.49.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.49.Final.jar!/:4.1.49.Final]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_91]

2020-05-26 14:14:05.050 DEBUG 25620 --- [actor-tcp-nio-4] reactor.netty.ReactorNetty               : [id: 0x96f19b86, L:/10.10.36.105:9999 ! R:/10.10.36.105:58908] Non Removed handler: RSocketLengthCodec, context: ChannelHandlerContext(RSocketLengthCodec, [id: 0x96f19b86, L:/10.10.36.105:9999 ! R:/10.10.36.105:58908]), pipeline: DefaultChannelPipeline{(RSocketLengthCodec = io.rsocket.transport.netty.RSocketLengthCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
2020-05-26 14:14:05.051 DEBUG 25620 --- [actor-tcp-nio-4] reactor.netty.channel.FluxReceive        : [id: 0x96f19b86, L:/10.10.36.105:9999 ! R:/10.10.36.105:58908] Dropping frame PooledSlicedByteBuf(ridx: 0, widx: 75, cap: 75/75, unwrapped: PooledUnsafeDirectByteBuf(ridx: 737, widx: 737, cap: 1024)), 0 in buffer

**Comment by linux-china** [comment]
这个是之前的kotlinx.serialization引发的bug，在1.0.0.M2版本和master中已经修复，请更新到最新的master进行测试一下。 如果还有问题，告知一下对应最新版本的日期。
